const produk = require('./globalfunction/get_produk.js')
const config = require('./globalfunction/get_config.js')
const global = require('./layout/template5/global.js')
const layout = require('./layout/template5/template5.js')
const layout_1 = require('./component/template5/view/setupview.js')
const funct_pin  = require('./globalfunction/behind_pin.js')
const screen = require('./globalfunction/resize.js')
const footermanipulation =  require('./globalfunction/offcanvasshowfooter.js')
require('./globalfunction/isNumber.js')
require('./component/template5/function/show_keterangan.js')
require('./component/template5/function/favorite.js')
require('./component/template5/function/terjadwal.js')
require('./component/template5/function/getwilayah.js')
require('./component/template5/function/rincian_pembelian.js')
require('./component/template5/function/findwilayah.js')
require('./component/template5/function/set_produk.js')
require('./component/template5/function/injectAndroid.js')
require('./component/template5/view/view_cek.js')
require('./component/template5/function/bayar.js')
global.data_produk = produk.get_data()
global.data_config = config.get_config()
document.querySelector('#main_el').innerHTML = layout.html()
layout_1.setupview(global.data_config,global.data_produk)
footermanipulation.off_footer()
screen.set_heightscreen()
screen.set_resize()
funct_pin.get_pin()
