const produk = require('./globalfunction/get_produk.js')
const config = require('./globalfunction/get_config.js')
const global  = require('./layout/template3/global.js')
const layout = require('./layout/template3/template3.js')
const layout_1 = require('./component/template3/view/setupview.js')
const layout_2 = require('./component/template3/view/setupviewproduk.js')
const footermanipulation =  require('./globalfunction/offcanvasshowfooter.js')
const funct_pin  = require('./globalfunction/behind_pin.js')
const screen = require('./globalfunction/resize.js')
global.data_produk = produk.get_data()
global.data_config = config.get_config()
require('./globalfunction/isNumber.js')
require('./component/template3/function/show_keterangan.js')
require('./component/template3/function/set_harga.js')
require('./component/template3/function/rincian_pembelian.js')
require('./component/template3/function/favorite.js')
require('./component/template3/function/terjadwal.js')
require('./component/template3/function/injectAndroid.js')
require('./component/template3/function/bayar.js')
require('./component/template3/view/view_cek.js')
document.querySelector('#main_el').innerHTML = layout.html()
layout_1.setupview(global.data_config)
layout_2.setup_view_harga(global.data_produk)
footermanipulation.off_footer()
screen.set_heightscreen()
screen.set_resize()
funct_pin.get_pin()
