const layout = require('./layout/template4/template4.js')
const layout_1 = require('./component/template4/view/setupview.js')
const layout_2 = require('./component/template4/view/setup_produk.js')
const global = require('./layout/template4/global.js')
const produk = require('./globalfunction/get_produk.js')
const config = require('./globalfunction/get_config.js')
const footermanipulation =  require('./globalfunction/offcanvasshowfooter.js')
const screen = require('./globalfunction/resize.js')
const funct_pin  = require('./globalfunction/behind_pin.js')
require('./component/template4/function/show_keterangan.js')
require('./component/template4/function/on_change_tujuan.js')
require('./component/template4/function/on_change_nominal.js')
require('./component/template4/function/on_scroll_produk.js')
require('./component/template4/function/on_click_produk.js')
require('./component/template4/function/rincian_pembelian.js')
require('./component/template4/view/view_cek.js')
require('./component/template4/function/bayar.js')
require('./component/template4/function/favorite.js')
require('./component/template4/function/injectAndroid.js')
require('./component/template4/function/terjadwal.js')
global.data_produk = produk.get_data()
global.data_config = config.get_config()
document.querySelector('#main_el').innerHTML = layout.html()
layout_1.setupview(global.data_config,global.data_produk)
layout_2.renderProduk(global.data_produk)
footermanipulation.off_footer()
screen.set_heightscreen()
screen.set_resize()
funct_pin.get_pin()
